// Package uuidv7 generates RFC 9562 UUIDv7 values: 48-bit unix-millisecond
// timestamp, then a 12-bit monotonic sequence (RFC 9562 §6.2 method 1) so
// IDs generated by one process are strictly increasing even within a single
// millisecond, then random bits. Lexicographic order therefore matches
// creation order, which the store relies on for ordering and latest-
// checkpoint queries.
package uuidv7

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"sync"
	"time"
)

var (
	mu     sync.Mutex
	lastMs uint64
	seq    uint16
)

// ShiftBack returns a synthetic UUIDv7-shaped lower bound: the id's
// embedded timestamp moved back by d, with zeroed entropy. Used as a sync
// cursor with an overlap window so cross-machine clock skew cannot hide
// events; idempotent import makes the overlap free.
func ShiftBack(id string, d time.Duration) string {
	if len(id) < 13 {
		return ""
	}
	hexTS := id[0:8] + id[9:13]
	var ms uint64
	if _, err := fmt.Sscanf(hexTS, "%012x", &ms); err != nil {
		return ""
	}
	back := uint64(d.Milliseconds())
	if back > ms {
		ms = 0
	} else {
		ms -= back
	}
	return fmt.Sprintf("%08x-%04x-7000-8000-000000000000", ms>>16, ms&0xffff)
}

// New returns a UUIDv7 string, strictly monotonic within this process.
func New() string {
	mu.Lock()
	ms := uint64(time.Now().UnixMilli())
	if ms <= lastMs {
		ms = lastMs
		seq++
		if seq > 0x0fff { // sequence exhausted: borrow the next millisecond
			ms++
			seq = 0
		}
	} else {
		seq = 0
	}
	lastMs = ms
	s := seq
	mu.Unlock()

	var b [16]byte
	b[0] = byte(ms >> 40)
	b[1] = byte(ms >> 32)
	b[2] = byte(ms >> 24)
	b[3] = byte(ms >> 16)
	b[4] = byte(ms >> 8)
	b[5] = byte(ms)
	b[6] = 0x70 | byte(s>>8) // version 7 + sequence high bits
	b[7] = byte(s)           // sequence low bits
	if _, err := rand.Read(b[8:]); err != nil {
		panic(err) // crypto/rand failure is unrecoverable
	}
	b[8] = (b[8] & 0x3f) | 0x80 // RFC variant
	dst := make([]byte, 36)
	hex.Encode(dst[0:8], b[0:4])
	dst[8] = '-'
	hex.Encode(dst[9:13], b[4:6])
	dst[13] = '-'
	hex.Encode(dst[14:18], b[6:8])
	dst[18] = '-'
	hex.Encode(dst[19:23], b[8:10])
	dst[23] = '-'
	hex.Encode(dst[24:36], b[10:16])
	return string(dst)
}
